import { useCallback, useEffect, useState } from 'react';
import { supabase } from '../supabase.ts';
import type { PatientRow } from './patients.ts';
import { useRealtimeRefresh } from '../useRealtimeRefresh.ts';
import { useStaleQueryLoading } from '../useStaleQueryLoading.ts';

export interface VisitRow {
  id: string;
  patient_id: string;
  location_id: string;
  appointment_id: string | null;
  walk_in_id: string | null;
  status: 'opened' | 'in_progress' | 'complete' | 'cancelled' | 'unsuitable';
  arrival_type: 'walk_in' | 'scheduled';
  receptionist_id: string | null;
  opened_at: string;
  closed_at: string | null;
  notes: string | null;
  // Immutable historical copy of the job box ref used during this
  // visit. Captured at insert time by trigger
  // lng_visits_capture_jb_ref_trg from the source row
  // (lng_appointments.jb_ref or lng_walk_ins.jb_ref). The source
  // values get nulled when the visit closes so the box becomes
  // available again; this column preserves the audit trail.
  jb_ref: string | null;
}

export interface CreateWalkInInput {
  patient_id: string;
  location_id: string;
  service_type?: string;
  notes?: string;
  // Stamped onto the new lng_walk_ins row so the lab can find the
  // patient's impression and the receptionist has a human-readable
  // reference. Generated by the arrival intake gate, which calls
  // generate_appointment_ref() on Postgres before this function runs.
  appointment_ref?: string;
  jb_ref?: string | null;
}

// Creates a walk-in + visit pair and writes a patient_events row.
// Returns the new visit + walk-in ids; the human-readable reference
// is the appointment_ref (LAP-NNNNN) already stamped on lng_walk_ins
// at intake-submit time.
export async function createWalkInVisit(
  input: CreateWalkInInput
): Promise<{ visit_id: string; opened_at: string; walk_in_id: string }> {
  const { data: walkIn, error: walkInErr } = await supabase
    .from('lng_walk_ins')
    .insert({
      patient_id: input.patient_id,
      location_id: input.location_id,
      arrival_type: 'walk_in',
      service_type: input.service_type ?? null,
      appointment_ref: input.appointment_ref ?? null,
      jb_ref: input.jb_ref ?? null,
    })
    .select('id')
    .single();
  if (walkInErr || !walkIn) throw new Error(walkInErr?.message ?? 'Could not create walk-in');

  // Return opened_at so the caller can pre-render the visit page's
  // breadcrumb timestamp on first paint instead of shimmering until
  // the post-navigation visit query resolves. The server's now() is
  // the canonical truth here, not a client-side new Date().
  const { data: visit, error: visitErr } = await supabase
    .from('lng_visits')
    .insert({
      patient_id: input.patient_id,
      location_id: input.location_id,
      walk_in_id: walkIn.id,
      arrival_type: 'walk_in',
      status: 'opened',
      notes: input.notes ?? null,
    })
    .select('id, opened_at')
    .single();
  if (visitErr || !visit) throw new Error(visitErr?.message ?? 'Could not create visit');

  await supabase.from('patient_events').insert({
    patient_id: input.patient_id,
    event_type: 'walk_in_arrived',
    payload: {
      visit_id: visit.id,
      walk_in_id: walkIn.id,
      appointment_ref: input.appointment_ref ?? null,
      service_type: input.service_type ?? null,
    },
  });

  // Calendar marker. Walk-ins live in lng_walk_ins + lng_visits, but the
  // schedule surfaces (today / week strip / patient timeline) read from
  // lng_appointments. Insert a marker row with source='manual' so the
  // walk-in shows up alongside Calendly bookings — the receptionist sees
  // a complete picture of who turned up today.
  //
  // walk_in_id is the FK back to lng_walk_ins so consumers that read
  // BOTH lng_appointments and lng_visits (the patient profile timeline,
  // for example) can dedup the marker against its visit with a single
  // equality check. The visit's appointment_id stays NULL — the
  // exactly-one constraint on lng_visits forces walk-ins to identify
  // their booking via walk_in_id, not appointment_id.
  const start = new Date();
  const end = new Date(start.getTime() + 30 * 60_000);
  await supabase.from('lng_appointments').insert({
    patient_id: input.patient_id,
    location_id: input.location_id,
    source: 'manual',
    start_at: start.toISOString(),
    end_at: end.toISOString(),
    event_type_label: 'Walk-in',
    status: 'arrived',
    walk_in_id: walkIn.id,
  });

  return {
    visit_id: visit.id,
    opened_at: (visit as { opened_at: string }).opened_at,
    walk_in_id: walkIn.id,
  };
}

// The reasons a receptionist can pick when flipping an appointment to
// no_show. Persisted to lng_appointments.cancel_reason and echoed in the
// patient_events.no_show payload so reports can break no-shows down by
// cause without re-reading the appointments row.
export type NoShowReason = 'did_not_turn_up' | 'patient_cancelled_late' | 'clinic_cancelled' | 'other';

// Compact, human-friendly label for the visit crumb in a breadcrumb
// chain. Two shapes depending on whether the surrounding chain
// already carries the patient's identity:
//
//   includeName: true   -> "Ewa Deb's Appt. 29 Apr"   (no patient crumb)
//   includeName: false  -> "Appt. 29 Apr"             (patient already shown)
//
// Bare "Appointment, 29 Apr, 21:43" was the previous format and
// read like an inventory line — staff couldn't see whose
// appointment it was without dragging their eye across the chain.
// Date-only (no time) keeps the crumb short; time is rarely needed
// to orient — the page heading carries it when it matters.
export function formatVisitCrumb(opts: {
  name: string | null;
  openedAtIso: string;
  includeName: boolean;
}): string {
  const d = new Date(opts.openedAtIso);
  const date = Number.isNaN(d.getTime())
    ? opts.openedAtIso
    : d.toLocaleDateString('en-GB', { day: 'numeric', month: 'short' });
  const trimmed = opts.name?.trim();
  if (opts.includeName && trimmed) return `${trimmed}'s Appt. ${date}`;
  return `Appt. ${date}`;
}

export const NO_SHOW_REASONS: { value: NoShowReason; label: string }[] = [
  { value: 'did_not_turn_up', label: 'Did not turn up' },
  { value: 'patient_cancelled_late', label: 'Patient cancelled late' },
  { value: 'clinic_cancelled', label: 'Clinic cancelled' },
  { value: 'other', label: 'Other' },
];

export interface MarkNoShowContext {
  patientId: string | null;
  wasVirtual: boolean;
  joinedBeforeNoShow: boolean;
}

// Flips an appointment to no_show, stamping the reason on
// lng_appointments.cancel_reason and emitting a patient_events row so the
// timeline + reports both have the cause.
export async function markNoShow(
  appointmentId: string,
  reason: NoShowReason,
  context: MarkNoShowContext
): Promise<void> {
  const { error } = await supabase
    .from('lng_appointments')
    .update({ status: 'no_show', cancel_reason: reason })
    .eq('id', appointmentId);
  if (error) throw new Error(error.message);

  if (!context.patientId) return;
  await supabase.from('patient_events').insert({
    patient_id: context.patientId,
    event_type: 'no_show',
    payload: {
      appointment_id: appointmentId,
      reason,
      was_virtual: context.wasVirtual,
      joined_before_no_show: context.joinedBeforeNoShow,
    },
  });
}

// Reverses a no-show flag. Patient turned up late after staff already
// flipped them — restore the appointment's pre-no-show state so the
// normal arrival flow can run.
//
// We do *not* create or reopen a visit here. Earlier behaviour
// auto-created the lng_visit and bounced the receptionist straight
// to /visit/:id, skipping the entire arrival form (intake, JB ref,
// waivers). That meant a reversed no-show looked nothing like a
// proper arrival in the audit trail. Now: flip the status back and
// stop. The receptionist sees the appointment in its normal booked
// or arrived state on the schedule, and clicks Mark as arrived
// from there to re-enter the arrival flow.
//
// Status target:
//   • Visit already exists (rare — staff re-flagged after arrival
//     completed): restore to 'arrived', the visit is real.
//   • No visit: 'booked' — pre-arrival state, ready for the normal
//     Mark-as-arrived flow.
export async function reverseNoShow(
  appointmentId: string
): Promise<{ status: 'arrived' | 'booked'; has_visit: boolean }> {
  const { data: existingVisit } = await supabase
    .from('lng_visits')
    .select('id')
    .eq('appointment_id', appointmentId)
    .maybeSingle();

  const hasVisit = !!(existingVisit as { id: string } | null);
  const targetStatus: 'arrived' | 'booked' = hasVisit ? 'arrived' : 'booked';

  const { data: appt, error } = await supabase
    .from('lng_appointments')
    .update({ status: targetStatus })
    .eq('id', appointmentId)
    .select('id, patient_id, join_url')
    .single();
  if (error || !appt) throw new Error(error?.message ?? 'Could not undo no-show');
  const apptRow = appt as { id: string; patient_id: string; join_url: string | null };

  const { data: accountId } = await supabase.rpc('auth_account_id');

  await supabase.from('patient_events').insert({
    patient_id: apptRow.patient_id,
    event_type: 'no_show_reversed',
    payload: {
      appointment_id: apptRow.id,
      staff_account_id: accountId ?? null,
      reversed_at: new Date().toISOString(),
      restored_status: targetStatus,
      was_virtual: !!apptRow.join_url,
    },
  });

  return { status: targetStatus, has_visit: hasVisit };
}

// Records that staff joined a virtual meeting. Flips the appointment to
// 'arrived' (re-uses the existing status — virtual attendance is still
// "the patient turned up") and writes a patient_events row so the
// timeline shows when the meeting was actually attended. Does NOT create
// an lng_visit — virtual impressions don't need an EPOS visit lifecycle.
export async function markVirtualMeetingJoined(appointmentId: string): Promise<void> {
  const { data: appt, error: apptErr } = await supabase
    .from('lng_appointments')
    .update({ status: 'arrived' })
    .eq('id', appointmentId)
    .select('id, patient_id, location_id')
    .single();
  if (apptErr || !appt) throw new Error(apptErr?.message ?? 'Could not record join');

  const { data: accountId } = await supabase.rpc('auth_account_id');

  await supabase.from('patient_events').insert({
    patient_id: appt.patient_id,
    event_type: 'virtual_meeting_joined',
    payload: {
      appointment_id: appt.id,
      staff_account_id: accountId ?? null,
      joined_at: new Date().toISOString(),
    },
  });
}

export async function markAppointmentArrived(
  appointmentId: string
): Promise<{ visit_id: string; opened_at: string }> {
  const { data: appt, error: apptErr } = await supabase
    .from('lng_appointments')
    .update({ status: 'arrived' })
    .eq('id', appointmentId)
    .select('id, patient_id, location_id')
    .single();
  if (apptErr || !appt) throw new Error(apptErr?.message ?? 'Could not mark arrived');

  // Returning opened_at lets the caller pass it through router state
  // so the visit page's breadcrumb renders the timestamp on first
  // paint — no shimmer-then-pop transition.
  const { data: visit, error: visitErr } = await supabase
    .from('lng_visits')
    .insert({
      patient_id: appt.patient_id,
      location_id: appt.location_id,
      appointment_id: appt.id,
      arrival_type: 'scheduled',
      status: 'opened',
    })
    .select('id, opened_at')
    .single();
  if (visitErr || !visit) throw new Error(visitErr?.message ?? 'Could not create visit');

  await supabase.from('patient_events').insert({
    patient_id: appt.patient_id,
    event_type: 'visit_arrived',
    payload: { visit_id: visit.id, appointment_id: appt.id, source: 'calendly' },
  });

  return {
    visit_id: visit.id,
    opened_at: (visit as { opened_at: string }).opened_at,
  };
}

// Calendly deposit captured at booking time, surfaced through the visit
// so the Pay screen can deduct it from the bill. Null on walk-ins (no
// underlying appointment) and on Calendly bookings whose event type
// doesn't take a deposit.
//
// status = 'paid'   ready to credit at checkout
// status = 'failed' attempt recorded but not collected — the till must NOT
//                   credit it; receptionist should chase.
export interface AppointmentDeposit {
  pence: number;
  currency: string;
  provider: 'paypal' | 'stripe';
  status: 'paid' | 'failed';
}

// Appointment context the visit page passes through to the catalogue
// picker so it can suggest matching products, and to the header so it
// can surface the appointment_ref and JB ref. Both surfaces are
// populated for booked appointments; walk-ins fill the same shape from
// lng_walk_ins so the visit page doesn't need to know which kind it
// landed on.
export interface VisitAppointmentContext {
  event_type_label: string | null;
  intake: Array<{ question: string; answer: string }> | null;
  appointment_ref: string | null;
  jb_ref: string | null;
  // When the appointment row was first inserted — i.e. when the
  // booking was created (Calendly webhook delivery or manual
  // booking by reception). Drives the "Booked" line on VisitDetail.
  created_at: string;
  // When the appointment is scheduled to begin. For walk-ins this
  // is the marker row's start_at (set to the arrival moment), so
  // the receptionist sees a sensible "Scheduled" entry only on
  // truly-pre-booked rows — VisitDetail gates on arrival_type to
  // decide whether to render this line.
  start_at: string;
  // Source of the booking ('calendly', 'manual', etc.). Used to
  // tweak the "Booked" copy when shown.
  source: string | null;
}

// Visits currently in progress at the receptionist's location. RLS scopes
// the query — every signed-in receptionist sees their own clinic. Used by
// the In-clinic route as the live "who's here right now" board.
export interface ActiveVisitRow {
  id: string;
  patient_id: string;
  status: 'opened' | 'in_progress';
  arrival_type: 'walk_in' | 'scheduled';
  opened_at: string;
  patient_first_name: string | null;
  patient_last_name: string | null;
  patient_phone: string | null;
}

interface ActiveVisitsResult {
  data: ActiveVisitRow[];
  loading: boolean;
  error: string | null;
  refresh: () => void;
}

export function useActiveVisits(): ActiveVisitsResult {
  const [data, setData] = useState<ActiveVisitRow[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [tick, setTick] = useState(0);
  const refresh = useCallback(() => setTick((t) => t + 1), []);
  const { loading, settle } = useStaleQueryLoading('active-visits');

  useEffect(() => {
    let cancelled = false;
    (async () => {
      const { data: rows, error: err } = await supabase
        .from('lng_visits')
        .select(
          'id, patient_id, status, arrival_type, opened_at, patient:patients ( first_name, last_name, phone )'
        )
        .in('status', ['opened', 'in_progress'])
        .order('opened_at', { ascending: true });
      if (cancelled) return;
      if (err) {
        if (err.code === 'PGRST200' || err.code === '42P01') {
          setData([]);
          setError(null);
        } else {
          setError(err.message);
        }
        settle();
        return;
      }
      const mapped: ActiveVisitRow[] = (rows ?? []).map((r) => {
        const raw = r as {
          id: string;
          patient_id: string;
          status: 'opened' | 'in_progress';
          arrival_type: 'walk_in' | 'scheduled';
          opened_at: string;
          patient:
            | { first_name: string | null; last_name: string | null; phone: string | null }
            | { first_name: string | null; last_name: string | null; phone: string | null }[]
            | null;
        };
        const p = Array.isArray(raw.patient) ? raw.patient[0] : raw.patient;
        return {
          id: raw.id,
          patient_id: raw.patient_id,
          status: raw.status,
          arrival_type: raw.arrival_type,
          opened_at: raw.opened_at,
          patient_first_name: p?.first_name ?? null,
          patient_last_name: p?.last_name ?? null,
          patient_phone: p?.phone ?? null,
        };
      });
      setData(mapped);
      settle();
    })();
    return () => {
      cancelled = true;
    };
  }, [tick, settle]);

  // The In-Clinic page and the BottomNav counter both consume this hook.
  // Subscribing to lng_visits covers status flips (opened → in_progress
  // → done) and new arrivals; lng_appointments covers the moment an
  // appointment is marked arrived (which spawns the visit row that
  // belongs in this list).
  useRealtimeRefresh(
    [
      { table: 'lng_visits' },
      { table: 'lng_appointments' },
    ],
    refresh,
  );

  return { data, loading, error, refresh };
}

interface VisitDetailResult {
  visit: VisitRow | null;
  patient: PatientRow | null;
  deposit: AppointmentDeposit | null;
  appointment: VisitAppointmentContext | null;
  // Display name of the receptionist who opened the visit. Resolved
  // from lng_visits.receptionist_id → accounts. Surfaces on printed
  // documents (LWO header) and the visit lifecycle strip; null when
  // the column isn't populated or the account row was deleted.
  receptionistName: string | null;
  loading: boolean;
  error: string | null;
  refresh: () => void;
}

export function useVisitDetail(visitId: string | undefined): VisitDetailResult {
  const [visit, setVisit] = useState<VisitRow | null>(null);
  const [patient, setPatient] = useState<PatientRow | null>(null);
  const [deposit, setDeposit] = useState<AppointmentDeposit | null>(null);
  const [appointment, setAppointment] = useState<VisitAppointmentContext | null>(null);
  const [receptionistName, setReceptionistName] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [tick, setTick] = useState(0);
  const { loading, settle } = useStaleQueryLoading(visitId);

  const refresh = useCallback(() => setTick((t) => t + 1), []);

  useEffect(() => {
    if (!visitId) {
      settle();
      return;
    }
    let cancelled = false;
    (async () => {
      const { data: v, error: ve } = await supabase
        .from('lng_visits')
        .select('*')
        .eq('id', visitId)
        .maybeSingle();
      if (cancelled) return;
      if (ve) {
        setError(ve.message);
        settle();
        return;
      }
      setVisit(v as VisitRow);
      if (v) {
        const visitRow = v as VisitRow;
        const { data: p } = await supabase
          .from('patients')
          .select(
            'id, location_id, internal_ref, first_name, last_name, email, phone, date_of_birth, shopify_customer_id'
          )
          .eq('id', visitRow.patient_id)
          .maybeSingle();
        if (!cancelled) setPatient(p as PatientRow | null);

        // Pull the deposit + intake refs off the linked appointment (if
        // any). For walk-ins, pull the same shape from lng_walk_ins so
        // the visit page doesn't have to special-case which kind it
        // is. The 42703 fallback survives a frontend deploy that lands
        // before the appointment_ref / jb_ref migrations.
        if (visitRow.appointment_id) {
          const { data: appt, error: apptErr } = await supabase
            .from('lng_appointments')
            .select(
              'event_type_label, intake, deposit_pence, deposit_currency, deposit_provider, deposit_status, appointment_ref, jb_ref, created_at, start_at, source'
            )
            .eq('id', visitRow.appointment_id)
            .maybeSingle();
          if (!cancelled && !apptErr && appt) {
            const a = appt as {
              event_type_label: string | null;
              intake: Array<{ question: string; answer: string }> | null;
              deposit_pence: number | null;
              deposit_currency: string | null;
              deposit_provider: 'paypal' | 'stripe' | null;
              deposit_status: 'paid' | 'failed' | null;
              appointment_ref: string | null;
              jb_ref: string | null;
              created_at: string;
              start_at: string;
              source: string | null;
            };
            setAppointment({
              event_type_label: a.event_type_label,
              intake: a.intake,
              appointment_ref: a.appointment_ref ?? null,
              jb_ref: a.jb_ref ?? null,
              created_at: a.created_at,
              start_at: a.start_at,
              source: a.source,
            });
            if (
              a.deposit_pence != null &&
              a.deposit_pence > 0 &&
              a.deposit_provider &&
              a.deposit_status
            ) {
              setDeposit({
                pence: a.deposit_pence,
                currency: a.deposit_currency ?? 'GBP',
                provider: a.deposit_provider,
                status: a.deposit_status,
              });
            } else {
              setDeposit(null);
            }
          }
        } else if (visitRow.walk_in_id) {
          const { data: wk, error: wkErr } = await supabase
            .from('lng_walk_ins')
            .select('service_type, appointment_ref, jb_ref, created_at')
            .eq('id', visitRow.walk_in_id)
            .maybeSingle();
          if (!cancelled && !wkErr && wk) {
            const w = wk as {
              service_type: string | null;
              appointment_ref: string | null;
              jb_ref: string | null;
              created_at: string;
            };
            setAppointment({
              event_type_label: w.service_type, // best-effort label for the catalogue picker
              intake: null,
              appointment_ref: w.appointment_ref ?? null,
              jb_ref: w.jb_ref ?? null,
              // Walk-ins have no booking lifecycle, but VisitDetail
              // expects these fields shaped the same as appointments
              // — gating on arrival_type keeps Booked/Scheduled
              // lines off the page for walk-ins.
              created_at: w.created_at,
              start_at: w.created_at,
              source: 'walk_in',
            });
            setDeposit(null);
          } else {
            setAppointment(null);
            setDeposit(null);
          }
        } else {
          setAppointment(null);
          setDeposit(null);
        }

        // Resolve the receptionist's display name. lng_visits stores
        // an account id; the printable LWO and any future audit
        // surface need a human-readable name. A missing account row
        // (deleted staff) leaves the name null and downstream renders
        // a dash — it never blocks the visit page from loading.
        if (visitRow.receptionist_id) {
          const { data: acct } = await supabase
            .from('accounts')
            .select('name, first_name, last_name')
            .eq('id', visitRow.receptionist_id)
            .maybeSingle();
          if (!cancelled) {
            const a = acct as { name: string | null; first_name: string | null; last_name: string | null } | null;
            const composed =
              (a?.name && a.name.trim()) ||
              [a?.first_name, a?.last_name].filter(Boolean).join(' ').trim();
            setReceptionistName(composed || null);
          }
        } else if (!cancelled) {
          setReceptionistName(null);
        }
      }
      settle();
    })();
    return () => {
      cancelled = true;
    };
  }, [visitId, tick, settle]);

  // Visit detail refreshes when its visit row, the linked appointment
  // (deposit status, JB ref, intake), or the underlying patient row
  // changes — so opening the till or running the customers/update
  // webhook is reflected on the page without a reload.
  useRealtimeRefresh(
    visitId
      ? [
          { table: 'lng_visits', filter: `id=eq.${visitId}` },
          { table: 'lng_appointments' },
          { table: 'patients' },
        ]
      : [],
    refresh,
  );

  return { visit, patient, deposit, appointment, receptionistName, loading, error, refresh };
}

// ---------- Unsuitability ----------

export interface RecordUnsuitabilityInput {
  patient_id: string;
  visit_id: string;
  catalogue_ids: string[];
  reason: string;
  // True when every line on the visit is being marked unsuitable —
  // the visit then terminates (status flips to 'unsuitable'). False
  // when only some lines are marked: records are filed but the visit
  // stays open so the remaining items can still be paid for.
  endsVisit: boolean;
}

// Files one immutable unsuitability record per chosen catalogue item,
// all sharing the same reason. When endsVisit=true (caller has told us
// every line on the visit is being marked), flips the visit to
// 'unsuitable' so it terminates and drops off the in-clinic board.
// Otherwise the visit stays open. Always writes one patient_events
// row so the timeline carries the audit trail.
export async function recordUnsuitability(input: RecordUnsuitabilityInput): Promise<void> {
  const reason = input.reason.trim();
  if (reason.length === 0) throw new Error('Reason is required');
  if (input.catalogue_ids.length === 0) throw new Error('At least one product is required');

  const { data: accountId } = await supabase.rpc('auth_account_id');

  // Insert one row per chosen product in a single round-trip. If the
  // batch fails (RLS, FK, length check) we bail without touching the
  // visit or the timeline — failing closed is the right default for
  // an audit-grade action.
  const rows = input.catalogue_ids.map((catalogue_id) => ({
    patient_id: input.patient_id,
    visit_id: input.visit_id,
    catalogue_id,
    reason,
    recorded_by: (accountId as string | null) ?? null,
  }));
  const { error: recErr } = await supabase.from('lng_unsuitability_records').insert(rows);
  if (recErr) throw new Error(recErr.message);

  // Only terminate the visit when every line was unsuitable. Partial
  // submissions leave the visit open so the remaining lines can still
  // be paid for (and printed, signed, etc.).
  if (input.endsVisit) {
    const { error: visitErr } = await supabase
      .from('lng_visits')
      .update({ status: 'unsuitable', closed_at: new Date().toISOString() })
      .eq('id', input.visit_id);
    if (visitErr) throw new Error(visitErr.message);
  }

  // Timeline row. One per submission — the payload carries every
  // catalogue_id that was flagged plus whether this submission ended
  // the visit, so the timeline summary can render the full picture
  // without joining back to lng_unsuitability_records.
  // Best-effort: we don't roll back the records + status flip if this
  // fails, since the audit trail is the source of truth.
  await supabase.from('patient_events').insert({
    patient_id: input.patient_id,
    event_type: 'patient_unsuitable_recorded',
    actor_account_id: (accountId as string | null) ?? null,
    notes: reason,
    payload: {
      visit_id: input.visit_id,
      catalogue_ids: input.catalogue_ids,
      reason,
      ended_visit: input.endsVisit,
      staff_account_id: (accountId as string | null) ?? null,
    },
  });
}

export interface ReverseUnsuitabilityInput {
  patient_id: string;
  visit_id: string;
}

// Reverses the visit-level "unsuitable" terminus. Records in
// lng_unsuitability_records stay as audit (we never mutate signed-off
// records). Visit goes back to in_progress with closed_at cleared so
// the cart is workable again. A patient_events row carries the
// reverse for the timeline.
export async function reverseUnsuitability(input: ReverseUnsuitabilityInput): Promise<void> {
  const { data: accountId } = await supabase.rpc('auth_account_id');

  const { error: visitErr } = await supabase
    .from('lng_visits')
    .update({ status: 'in_progress', closed_at: null })
    .eq('id', input.visit_id);
  if (visitErr) throw new Error(visitErr.message);

  await supabase.from('patient_events').insert({
    patient_id: input.patient_id,
    event_type: 'patient_unsuitable_reversed',
    actor_account_id: (accountId as string | null) ?? null,
    payload: {
      visit_id: input.visit_id,
      staff_account_id: (accountId as string | null) ?? null,
    },
  });
}

// Latest unsuitability record on a visit, joined to the recording
// staff member's account so the header can render "By [name]". Null
// while no records exist yet.
export interface LatestUnsuitability {
  recorded_at: string;
  reason: string;
  recorded_by_name: string | null;
}

interface LatestUnsuitabilityResult {
  data: LatestUnsuitability | null;
  loading: boolean;
  error: string | null;
}

export function useLatestUnsuitability(visitId: string | null): LatestUnsuitabilityResult {
  const [data, setData] = useState<LatestUnsuitability | null>(null);
  const [error, setError] = useState<string | null>(null);
  const { loading, settle } = useStaleQueryLoading(visitId);

  useEffect(() => {
    if (!visitId) {
      setData(null);
      settle();
      return;
    }
    let cancelled = false;
    (async () => {
      const { data: row, error: err } = await supabase
        .from('lng_unsuitability_records')
        .select('recorded_at, reason, recorded_by, account:accounts!recorded_by ( first_name, last_name, name )')
        .eq('visit_id', visitId)
        .order('recorded_at', { ascending: false })
        .limit(1)
        .maybeSingle();
      if (cancelled) return;
      if (err) {
        if (err.code === '42P01' || err.code === 'PGRST200') {
          setData(null);
          setError(null);
        } else {
          setError(err.message);
        }
        settle();
        return;
      }
      if (!row) {
        setData(null);
        settle();
        return;
      }
      const r = row as {
        recorded_at: string;
        reason: string;
        recorded_by: string | null;
        account:
          | { first_name: string | null; last_name: string | null; name: string | null }
          | { first_name: string | null; last_name: string | null; name: string | null }[]
          | null;
      };
      const a = Array.isArray(r.account) ? r.account[0] ?? null : r.account ?? null;
      const fn = a?.first_name?.trim();
      const ln = a?.last_name?.trim();
      const display = fn && ln ? `${fn} ${ln}` : fn ?? ln ?? a?.name?.trim() ?? null;
      setData({
        recorded_at: r.recorded_at,
        reason: r.reason,
        recorded_by_name: display,
      });
      settle();
    })();
    return () => {
      cancelled = true;
    };
  }, [visitId, settle]);

  return { data, loading, error };
}
