import { useCallback, useEffect, useState } from 'react';
import { supabase } from '../supabase.ts';
import type { PatientRow } from './patients.ts';
import { useRealtimeRefresh } from '../useRealtimeRefresh.ts';
import { useStaleQueryLoading } from '../useStaleQueryLoading.ts';
import { sendAppointmentConfirmation } from './sendAppointmentConfirmation.ts';
import { logFailure } from '../failureLog.ts';

export interface VisitRow {
  id: string;
  patient_id: string;
  location_id: string;
  appointment_id: string | null;
  walk_in_id: string | null;
  status: 'arrived' | 'complete' | 'unsuitable' | 'ended_early';
  arrival_type: 'walk_in' | 'scheduled';
  receptionist_id: string | null;
  opened_at: string;
  closed_at: string | null;
  notes: string | null;
  // Immutable historical copy of the job box ref used during this
  // visit. Captured at insert time by trigger
  // lng_visits_capture_jb_ref_trg from the source row
  // (lng_appointments.jb_ref or lng_walk_ins.jb_ref). The source
  // values get nulled when the visit closes so the box becomes
  // available again; this column preserves the audit trail.
  jb_ref: string | null;
  // Set when status flips to 'complete' via the Finish visit sheet.
  fulfilment_method: 'in_person' | 'shipping' | null;
  // Dispatch columns — populated by book-lng-shipment when
  // fulfilment_method='shipping' and the DPD label is created.
  dispatched_at:    string | null;
  dispatched_by:    string | null;
  tracking_number:  string | null;
  // parcel_code includes the depot suffix (e.g. 15976969376288*21297) and
  // is required to build a working DPD tracking URL. tracking_number alone
  // resolves to the wrong URL.
  parcel_code:      string | null;
  shipment_id:      string | null;
  label_data:       string | null;
  shipping_address: {
    name: string;
    address1: string;
    address2: string;
    city: string;
    zip: string;
    country_code: string;
    phone: string;
  } | null;
  dispatch_ref:          string | null;
  shipping_email_sent_at: string | null;
}

export interface CreateWalkInInput {
  patient_id: string;
  location_id: string;
  service_type?: string;
  // Catalogue axis pins. Used to compose the schedule / hero label
  // through formatAppointmentSummary the same way a native widget
  // booking does, so a walk-in for a snapped denture reads "Denture
  // Repair" instead of the bare "Walk-in" fallback. Pass when known;
  // null otherwise.
  arch?: string | null;
  product_key?: string | null;
  repair_variant?: string | null;
  notes?: string;
  // Stamped onto the new lng_walk_ins row so the lab can find the
  // patient's impression and the receptionist has a human-readable
  // reference. Generated by the arrival intake gate, which calls
  // generate_appointment_ref() on Postgres before this function runs.
  appointment_ref?: string;
  jb_ref?: string | null;
}

// Creates a walk-in + visit pair and writes a patient_events row.
// Returns the new visit + walk-in ids; the human-readable reference
// is the appointment_ref (LAP-NNNNN) already stamped on lng_walk_ins
// at intake-submit time.
export async function createWalkInVisit(
  input: CreateWalkInInput
): Promise<{ visit_id: string; opened_at: string; walk_in_id: string }> {
  const { data: walkIn, error: walkInErr } = await supabase
    .from('lng_walk_ins')
    .insert({
      patient_id: input.patient_id,
      location_id: input.location_id,
      arrival_type: 'walk_in',
      service_type: input.service_type ?? null,
      appointment_ref: input.appointment_ref ?? null,
      jb_ref: input.jb_ref ?? null,
    })
    .select('id')
    .single();
  if (walkInErr || !walkIn) throw new Error(walkInErr?.message ?? 'Could not create walk-in');

  // Stamp the receptionist who took the walk-in so the timeline's
  // "Walk-in arrived" + "Job box assigned" events attribute by
  // [name]. NULL on resolver failure rather than blocking arrival.
  const { data: walkInAccountId } = await supabase.rpc('auth_account_id');

  // Return opened_at so the caller can pre-render the visit page's
  // breadcrumb timestamp on first paint instead of shimmering until
  // the post-navigation visit query resolves. The server's now() is
  // the canonical truth here, not a client-side new Date().
  const { data: visit, error: visitErr } = await supabase
    .from('lng_visits')
    .insert({
      patient_id: input.patient_id,
      location_id: input.location_id,
      walk_in_id: walkIn.id,
      arrival_type: 'walk_in',
      status: 'arrived',
      notes: input.notes ?? null,
      receptionist_id: (walkInAccountId as string | null) ?? null,
    })
    .select('id, opened_at')
    .single();
  if (visitErr || !visit) throw new Error(visitErr?.message ?? 'Could not create visit');

  await supabase.from('patient_events').insert({
    patient_id: input.patient_id,
    event_type: 'walk_in_arrived',
    actor_account_id: (walkInAccountId as string | null) ?? null,
    payload: {
      visit_id: visit.id,
      walk_in_id: walkIn.id,
      appointment_ref: input.appointment_ref ?? null,
      service_type: input.service_type ?? null,
    },
  });

  // Calendar marker. Walk-ins live in lng_walk_ins + lng_visits, but the
  // schedule surfaces (today / week strip / patient timeline) read from
  // lng_appointments. Insert a marker row with source='manual' so the
  // walk-in shows up alongside scheduled bookings — the receptionist
  // sees a complete picture of who turned up today.
  //
  // walk_in_id is the FK back to lng_walk_ins so consumers that read
  // BOTH lng_appointments and lng_visits (the patient profile timeline,
  // for example) can dedup the marker against its visit with a single
  // equality check. The visit's appointment_id stays NULL — the
  // exactly-one constraint on lng_visits forces walk-ins to identify
  // their booking via walk_in_id, not appointment_id.
  const start = new Date();
  const end = new Date(start.getTime() + 30 * 60_000);
  const { data: markerRaw } = await supabase
    .from('lng_appointments')
    .insert({
      patient_id: input.patient_id,
      location_id: input.location_id,
      source: 'manual',
      // created_via lets audits + reports distinguish a walk-in
      // marker from a staff-booked manual appointment. Both carry
      // source='manual' (they are not Calendly / native widget
      // bookings); only this column captures the operational
      // distinction.
      created_via: 'walk_in',
      start_at: start.toISOString(),
      end_at: end.toISOString(),
      // Carry the picked service axis onto the marker so every
      // surface that runs the row through formatAppointmentSummary
      // renders "Denture Repair" / "Same-day Lower Retainer" etc.
      // instead of the bare "Walk-in" fallback. The marker was
      // previously written with service_type = null and an
      // event_type_label of 'Walk-in', which meant the Schedule
      // click sheet, the patient timeline, and the visit-side
      // hero all read "Walk-in" as the booking title regardless
      // of what the receptionist actually staged. Walk-ins still
      // identify themselves as walk-ins via walk_in_id IS NOT
      // NULL — the schedule renders a "Walk-in" prefix when that
      // FK is set, so we don't lose that signal by populating the
      // service axis here. event_type_label stays as a fallback
      // for the 'other' / null service cases where the formatter
      // returns the persisted label.
      service_type: input.service_type ?? null,
      arch: input.arch ?? null,
      product_key: input.product_key ?? null,
      repair_variant: input.repair_variant ?? null,
      event_type_label: 'Walk-in',
      status: 'arrived',
      walk_in_id: walkIn.id,
    })
    .select('id')
    .single();
  const markerId = (markerRaw as { id: string } | null)?.id ?? null;

  // Mirror appointment_booked for the marker so reports that roll up
  // "every booking that landed in the schedule" don't have to special-
  // case walk-ins. visitTimeline.ts already filters appointment_booked
  // out of the visit-side feed (walk_in_arrived owns the visual row),
  // so this is audit-only and doesn't double up the UI. Best-effort —
  // a failure here doesn't unwind the walk-in.
  if (markerId) {
    await supabase.from('patient_events').insert({
      patient_id: input.patient_id,
      event_type: 'appointment_booked',
      actor_account_id: (walkInAccountId as string | null) ?? null,
      payload: {
        appointment_id: markerId,
        walk_in_id: walkIn.id,
        source: 'walk_in_marker',
        service_type: input.service_type ?? null,
        start_at: start.toISOString(),
        end_at: end.toISOString(),
      },
    });
  }

  return {
    visit_id: visit.id,
    opened_at: (visit as { opened_at: string }).opened_at,
    walk_in_id: walkIn.id,
  };
}

// The reasons a receptionist can pick when flipping an appointment to
// no_show. Persisted to lng_appointments.cancel_reason and echoed in the
// patient_events.no_show payload so reports can break no-shows down by
// cause without re-reading the appointments row.
export type NoShowReason = 'did_not_turn_up' | 'patient_cancelled_late' | 'clinic_cancelled' | 'other';

// Compact, human-friendly label for the visit crumb in a breadcrumb
// chain. Two shapes depending on whether the surrounding chain
// already carries the patient's identity:
//
//   includeName: true   -> "Ewa Deb's Appt. 29 Apr"   (no patient crumb)
//   includeName: false  -> "Appt. 29 Apr"             (patient already shown)
//
// Bare "Appointment, 29 Apr, 21:43" was the previous format and
// read like an inventory line — staff couldn't see whose
// appointment it was without dragging their eye across the chain.
// Date-only (no time) keeps the crumb short; time is rarely needed
// to orient — the page heading carries it when it matters.
export function formatVisitCrumb(opts: {
  name: string | null;
  openedAtIso: string;
  includeName: boolean;
}): string {
  const d = new Date(opts.openedAtIso);
  const date = Number.isNaN(d.getTime())
    ? opts.openedAtIso
    : d.toLocaleDateString('en-GB', { day: 'numeric', month: 'short' });
  const trimmed = opts.name?.trim();
  if (opts.includeName && trimmed) return `${trimmed}'s Appt. ${date}`;
  return `Appt. ${date}`;
}

export const NO_SHOW_REASONS: { value: NoShowReason; label: string }[] = [
  { value: 'did_not_turn_up', label: 'Did not turn up' },
  { value: 'patient_cancelled_late', label: 'Patient cancelled late' },
  { value: 'clinic_cancelled', label: 'Clinic cancelled' },
  { value: 'other', label: 'Other' },
];

// Humanise lng_appointments.cancel_reason. Handles:
//   • NoShowReason enum values — the four reasons the receptionist
//     picks from when marking a no-show (see NO_SHOW_REASONS).
//   • 'patient_self_serve' — written by the widget-cancel-booking
//     edge function when the patient cancels themselves from the
//     manage page link sent in their confirmation email.
//   • 'patient_self_serve_reschedule' — same, written on the OLD
//     row by widget-reschedule-booking when the patient moves
//     their own slot from the manage page. The NEW row carries
//     reschedule_to_id pointing at the replacement.
//   • Anything else — passed through verbatim. Operators can type
//     a free-text "Other" reason on the no-show sheet; we want that
//     to render exactly as they wrote it.
// Returns null on null/empty input so callers can render nothing.
export function humaniseCancelReason(
  reason: string | null | undefined,
): string | null {
  if (!reason) return null;
  const trimmed = reason.trim();
  if (!trimmed) return null;
  switch (trimmed) {
    case 'did_not_turn_up':
      return 'Did not turn up';
    case 'patient_cancelled_late':
      return 'Patient cancelled late';
    case 'clinic_cancelled':
      return 'Clinic cancelled';
    case 'other':
      return 'Other reason';
    case 'patient_self_serve':
      return 'Customer cancelled via the self-service link in their email';
    case 'patient_self_serve_reschedule':
      return 'Customer rescheduled via the self-service link in their email';
    default:
      return trimmed;
  }
}

export interface MarkNoShowContext {
  patientId: string | null;
  wasVirtual: boolean;
  joinedBeforeNoShow: boolean;
  // Optional override for what gets written to
  // lng_appointments.cancel_reason. Used when the receptionist picks
  // "Other" with a custom note — we store the typed text rather than
  // the bare 'other' enum so reports surface what actually happened.
  // The patient_events row keeps `reason: NoShowReason` so the
  // timeline can still bucket events by enum.
  storedReason?: string;
}

// Flips an appointment to no_show, stamping the reason on
// lng_appointments.cancel_reason and emitting a patient_events row so the
// timeline + reports both have the cause.
export async function markNoShow(
  appointmentId: string,
  reason: NoShowReason,
  context: MarkNoShowContext
): Promise<void> {
  const stored = context.storedReason?.trim() || reason;
  const { error } = await supabase
    .from('lng_appointments')
    .update({ status: 'no_show', cancel_reason: stored })
    .eq('id', appointmentId);
  if (error) throw new Error(error.message);

  if (!context.patientId) return;
  const { data: noShowAccountId } = await supabase.rpc('auth_account_id');
  await supabase.from('patient_events').insert({
    patient_id: context.patientId,
    event_type: 'no_show',
    actor_account_id: (noShowAccountId as string | null) ?? null,
    payload: {
      appointment_id: appointmentId,
      reason,
      // The custom text (when present) ships in `note` so the timeline
      // can show it without parsing cancel_reason for an enum/non-enum
      // distinction.
      note: context.storedReason?.trim() && reason === 'other' ? context.storedReason.trim() : undefined,
      was_virtual: context.wasVirtual,
      joined_before_no_show: context.joinedBeforeNoShow,
    },
  });

  // Best-effort no-show email dispatch. The edge function honours the
  // appointment_no_show template's `enabled` flag, which seeds disabled
  // per booking type — until Dylan writes the copy and switches the row
  // on, this returns reason: 'template_disabled' and nothing leaves the
  // building. Errors are swallowed: the status flip + patient_events
  // row are the source of truth; an email failure must never mask that
  // the no-show was recorded.
  try {
    await sendAppointmentConfirmation({
      appointmentId,
      intent: 'no_show',
    });
  } catch {
    // Intentional: see comment above.
  }
}

// Reverses a no-show flag. Patient turned up late after staff already
// flipped them — restore the appointment's pre-no-show state so the
// normal arrival flow can run.
//
// We do *not* create or reopen a visit here. Earlier behaviour
// auto-created the lng_visit and bounced the receptionist straight
// to /visit/:id, skipping the entire arrival form (intake, JB ref,
// waivers). That meant a reversed no-show looked nothing like a
// proper arrival in the audit trail. Now: flip the status back and
// stop. The receptionist sees the appointment in its normal booked
// or arrived state on the schedule, and clicks Mark as arrived
// from there to re-enter the arrival flow.
//
// Status target:
//   • Visit already exists (rare — staff re-flagged after arrival
//     completed): restore to 'arrived', the visit is real.
//   • No visit: 'booked' — pre-arrival state, ready for the normal
//     Mark-as-arrived flow.
export async function reverseNoShow(
  appointmentId: string
): Promise<{ status: 'arrived' | 'booked'; has_visit: boolean }> {
  const { data: existingVisit } = await supabase
    .from('lng_visits')
    .select('id')
    .eq('appointment_id', appointmentId)
    .maybeSingle();

  const hasVisit = !!(existingVisit as { id: string } | null);
  const targetStatus: 'arrived' | 'booked' = hasVisit ? 'arrived' : 'booked';

  const { data: appt, error } = await supabase
    .from('lng_appointments')
    .update({ status: targetStatus })
    .eq('id', appointmentId)
    .select('id, patient_id, join_url')
    .single();
  if (error || !appt) throw new Error(error?.message ?? 'Could not undo no-show');
  const apptRow = appt as { id: string; patient_id: string; join_url: string | null };

  const { data: accountId } = await supabase.rpc('auth_account_id');

  await supabase.from('patient_events').insert({
    patient_id: apptRow.patient_id,
    event_type: 'no_show_reversed',
    actor_account_id: (accountId as string | null) ?? null,
    payload: {
      appointment_id: apptRow.id,
      staff_account_id: accountId ?? null,
      reversed_at: new Date().toISOString(),
      restored_status: targetStatus,
      was_virtual: !!apptRow.join_url,
    },
  });

  return { status: targetStatus, has_visit: hasVisit };
}

// Records that staff joined a virtual meeting. Flips the appointment to
// 'joined' (virtual-specific — "arrived" is meaningless for a Google Meet)
// and writes a patient_events row so the timeline shows when the meeting
// was attended. Does NOT create an lng_visit — virtual appointments don't
// need an EPOS visit lifecycle.
export async function markVirtualMeetingJoined(appointmentId: string): Promise<void> {
  const { data: appt, error: apptErr } = await supabase
    .from('lng_appointments')
    .update({ status: 'joined' })
    .eq('id', appointmentId)
    .select('id, patient_id, location_id')
    .single();
  if (apptErr || !appt) throw new Error(apptErr?.message ?? 'Could not record join');

  const { data: accountId } = await supabase.rpc('auth_account_id');

  await supabase.from('patient_events').insert({
    patient_id: appt.patient_id,
    event_type: 'virtual_meeting_joined',
    actor_account_id: (accountId as string | null) ?? null,
    payload: {
      appointment_id: appt.id,
      staff_account_id: accountId ?? null,
      joined_at: new Date().toISOString(),
    },
  });
}

// Marks a virtual appointment as complete. The call is done — flips
// status to 'complete' and writes a patient_events row for the timeline.
// Virtual appointments don't create visits, so this is the terminal
// happy-path state (the counterpart to completeVisit for in-person).
export async function markVirtualComplete(appointmentId: string): Promise<void> {
  const { data: appt, error } = await supabase
    .from('lng_appointments')
    .update({ status: 'complete' })
    .eq('id', appointmentId)
    .select('id, patient_id')
    .single();
  if (error || !appt) throw new Error(error?.message ?? 'Could not complete virtual call');

  const { data: accountId } = await supabase.rpc('auth_account_id');

  await supabase.from('patient_events').insert({
    patient_id: appt.patient_id,
    event_type: 'virtual_call_completed',
    actor_account_id: (accountId as string | null) ?? null,
    payload: {
      appointment_id: appt.id,
      staff_account_id: (accountId as string | null) ?? null,
      completed_at: new Date().toISOString(),
    },
  });
}

// Records that staff rejoined an already-joined virtual meeting. No
// status flip — the appointment stays 'joined'. Writes a patient_events
// row so the timeline tracks every time the link was reopened.
//
// Throws on insert error rather than silently swallowing it. The
// previous version awaited `.insert()` without checking the response
// — Supabase doesn't reject on RLS denial, it returns the error in
// the response object — so an RLS misconfiguration would make every
// Rejoin tap appear to succeed while writing nothing. The caller in
// AppointmentDetail catches the throw and forwards it to logFailure
// so the audit trail stays loud.
export async function logVirtualMeetingRejoin(appointmentId: string, patientId: string): Promise<void> {
  const { data: accountId } = await supabase.rpc('auth_account_id');
  const { error } = await supabase.from('patient_events').insert({
    patient_id: patientId,
    event_type: 'virtual_meeting_rejoined',
    actor_account_id: (accountId as string | null) ?? null,
    payload: {
      appointment_id: appointmentId,
      rejoined_at: new Date().toISOString(),
    },
  });
  if (error) throw new Error(error.message);
}

export interface MarkAppointmentArrivedInput {
  appointment_id: string;
  // Tech note typed on the arrival form's Step 1 (Service). Carries
  // straight to lng_visits.notes so VisitDetail's "Edit tech note"
  // button reads what the receptionist captured at arrival rather
  // than showing "Add tech note" on a visit that already has one.
  // Pre-RPC, only the walk-in path wrote this; appointment arrivals
  // silently dropped the textarea on the floor.
  notes?: string;
}

export async function markAppointmentArrived(
  input: MarkAppointmentArrivedInput
): Promise<{ visit_id: string; opened_at: string }> {
  const trimmedNotes = input.notes?.trim();
  const notesToWrite = trimmedNotes && trimmedNotes.length > 0 ? trimmedNotes : null;

  const { data: appt, error: apptErr } = await supabase
    .from('lng_appointments')
    .update({ status: 'arrived' })
    .eq('id', input.appointment_id)
    .select('id, patient_id, location_id')
    .single();
  if (apptErr || !appt) throw new Error(apptErr?.message ?? 'Could not mark arrived');

  // Stamp the receptionist who checked the patient in so the
  // timeline's "Patient checked in" + "Job box assigned" events can
  // attribute by [name]. Best-effort: if the account resolver fails
  // (kiosk session edge case) the column lands NULL rather than
  // blocking arrival.
  const { data: accountIdAtArrival } = await supabase.rpc('auth_account_id');
  const receptionistId = (accountIdAtArrival as string | null) ?? null;

  // Returning opened_at lets the caller pass it through router state
  // so the visit page's breadcrumb renders the timestamp on first
  // paint — no shimmer-then-pop transition.
  const { data: visit, error: visitErr } = await supabase
    .from('lng_visits')
    .insert({
      patient_id: appt.patient_id,
      location_id: appt.location_id,
      appointment_id: appt.id,
      arrival_type: 'scheduled',
      status: 'arrived',
      receptionist_id: receptionistId,
      notes: notesToWrite,
    })
    .select('id, opened_at')
    .single();
  if (visitErr || !visit) throw new Error(visitErr?.message ?? 'Could not create visit');

  await supabase.from('patient_events').insert({
    patient_id: appt.patient_id,
    event_type: 'visit_arrived',
    actor_account_id: receptionistId,
    payload: { visit_id: visit.id, appointment_id: appt.id, source: 'calendly' },
  });

  return {
    visit_id: visit.id,
    opened_at: (visit as { opened_at: string }).opened_at,
  };
}

// Calendly deposit captured at booking time, surfaced through the visit
// so the Pay screen can deduct it from the bill. Null on walk-ins (no
// underlying appointment) and on Calendly bookings whose event type
// doesn't take a deposit.
//
// status = 'paid'   ready to credit at checkout
// status = 'failed' attempt recorded but not collected — the till must NOT
//                   credit it; receptionist should chase.
export interface AppointmentDeposit {
  pence: number;
  currency: string;
  provider: 'paypal' | 'stripe';
  status: 'paid' | 'failed';
  // Where the booking + deposit originated. 'native' means the online
  // widget (venneir.com / denture-services.co.uk); 'calendly' means a
  // Calendly checkout. Drives the "via …" suffix on Pay screen and
  // waiver so a widget deposit doesn't read as a Calendly one.
  source: string | null;
  // brand_id of the booking — 'venneir' or 'denture'. Picks the
  // customer-facing domain in the source suffix ("venneir.com" vs
  // "denture-services.co.uk"). Null when the column wasn't populated
  // (legacy rows); callers default to 'venneir' for safety.
  brandId: 'venneir' | 'denture' | null;
  // True when the widget collected the FULL service price up-front,
  // not just a deposit. Pay screen + waiver use this to switch the
  // line label from "Deposit" to "Paid in full". Always false for
  // Calendly bookings (Calendly only takes deposits).
  paidInFullAtBooking: boolean;
}

/** Bracketed suffix shown after a deposit line on every staff
 *  surface (Pay screen, VisitDetail Cart, waiver PDF) — e.g.
 *  "Stripe via Calendly" / "Stripe via venneir.com" / "PayPal via
 *  denture-services.co.uk". Source 'native' means the online widget,
 *  with the brand id picking the customer-facing domain. Calendly
 *  deposits keep the legacy label so historical receipts stay
 *  consistent; null source defaults to Calendly so legacy rows
 *  written before the source/brand columns existed don't suddenly
 *  relabel. */
export function formatDepositSourceSuffix(deposit: AppointmentDeposit | null): string {
  const provider = deposit?.provider === 'stripe' ? 'Stripe' : 'PayPal';
  if (deposit?.source === 'native') {
    const brand = deposit.brandId === 'denture' ? 'denture-services.co.uk' : 'venneir.com';
    return `${provider} via ${brand}`;
  }
  return `${provider} via Calendly`;
}

// Shopify-paid order linked to an appointment at booking time. The
// total credits against the cart at checkout the same way the
// Calendly deposit does, and surfaces on the waiver as
// "Shopify order VEN73520 (paid online) −£X". Null on appointments
// that didn't come through a sold_on_shopify catalogue row.
export interface AppointmentShopifyOrder {
  id: string;
  name: string;
  pence: number;
  currency: string;
}

// Appointment context the visit page passes through to the catalogue
// picker so it can suggest matching products, and to the header so it
// can surface the appointment_ref and JB ref. Both surfaces are
// populated for booked appointments; walk-ins fill the same shape from
// lng_walk_ins so the visit page doesn't need to know which kind it
// landed on.
export interface VisitAppointmentContext {
  // Underlying lng_appointments.id — threaded through so VisitDetail
  // can pass it to the StaffNotesCard. The visit row already has
  // appointment_id, but having it here keeps the call sites uniform
  // ("read everything appointment-side off the context").
  id: string;
  // Legacy single-text note column on lng_appointments. Superseded
  // by lng_appointment_staff_notes (multi-note + audit) on 21 May
  // 2026; this field stays selected for backward-compat reads and
  // will be dropped in a follow-up migration once nothing still
  // touches it.
  notes: string | null;
  // Patient-typed widget note from lng_appointments.customer_note.
  // Read-only — surfaces in CustomerNoteHero above the staff CS note
  // so the floor team can see what the customer asked when they
  // booked without confusing it with internal handoff text.
  customer_note: string | null;
  event_type_label: string | null;
  intake: Array<{ question: string; answer: string }> | null;
  appointment_ref: string | null;
  jb_ref: string | null;
  // When the appointment row was first inserted — i.e. when the
  // booking was created (Calendly webhook delivery or manual
  // booking by reception). Drives the "Booked" line on VisitDetail.
  created_at: string;
  // When the appointment is scheduled to begin. For walk-ins this
  // is the marker row's start_at (set to the arrival moment), so
  // the receptionist sees a sensible "Scheduled" entry only on
  // truly-pre-booked rows — VisitDetail gates on arrival_type to
  // decide whether to render this line.
  start_at: string;
  // End of the scheduled slot — needed by the Reschedule sheet,
  // which seeds the duration field from end_at - start_at.
  end_at: string | null;
  // Location the appointment was booked into. Threaded through so
  // the Reschedule sheet can carry it without a second round-trip.
  location_id: string | null;
  // Source of the booking ('calendly', 'manual', etc.). Used to
  // tweak the "Booked" copy when shown.
  source: string | null;
  // Axis pins on the booking row. Native-widget bookings store
  // service_type / arch / product_key directly so VisitDetail's
  // hero title can compose "Upper Click-in veneers" / "Lower
  // retainer" etc. via formatNativeBookingSummary — matching how
  // AppointmentDetail's hero renders the same booking. Calendly-
  // imported rows leave service_type populated but arch /
  // product_key null; the formatter falls back to the
  // event_type_label in that case.
  service_type: string | null;
  arch: string | null;
  product_key: string | null;
  /** Denture-repair axis pin. Threaded through so the visit-page
   *  phase-timeline modal can resolve the correct child-override
   *  phase shape (denture_repair has per-variant overrides). Null
   *  for any service that doesn't index by repair variant. */
  repair_variant: string | null;
  /** Free same-day upgrade flag + reason (set by the Checkpoint booker).
   *  When true the till collects £0 for the appliance and a banner shows
   *  on the visit. Null/false for everything else. */
  free_upgrade: boolean | null;
  free_upgrade_reason: string | null;
}

// Visits currently in progress at the receptionist's location. RLS scopes
// the query — every signed-in receptionist sees their own clinic. Used by
// the In-clinic route as the live "who's here right now" board.
export interface ActiveVisitRow {
  id: string;
  patient_id: string;
  status: 'arrived';
  arrival_type: 'walk_in' | 'scheduled';
  opened_at: string;
  patient_first_name: string | null;
  patient_last_name: string | null;
  patient_phone: string | null;
}

interface ActiveVisitsResult {
  data: ActiveVisitRow[];
  loading: boolean;
  error: string | null;
  refresh: () => void;
}

export function useActiveVisits(): ActiveVisitsResult {
  const [data, setData] = useState<ActiveVisitRow[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [tick, setTick] = useState(0);
  const refresh = useCallback(() => setTick((t) => t + 1), []);
  const { loading, settle } = useStaleQueryLoading('active-visits');

  useEffect(() => {
    let cancelled = false;
    (async () => {
      const { data: rows, error: err } = await supabase
        .from('lng_visits')
        .select(
          'id, patient_id, status, arrival_type, opened_at, patient:patients ( first_name, last_name, phone )'
        )
        .eq('status', 'arrived')
        .order('opened_at', { ascending: true });
      if (cancelled) return;
      if (err) {
        if (err.code === 'PGRST200' || err.code === '42P01') {
          setData([]);
          setError(null);
        } else {
          setError(err.message);
        }
        settle();
        return;
      }
      const mapped: ActiveVisitRow[] = (rows ?? []).map((r) => {
        const raw = r as {
          id: string;
          patient_id: string;
          status: 'arrived';
          arrival_type: 'walk_in' | 'scheduled';
          opened_at: string;
          patient:
            | { first_name: string | null; last_name: string | null; phone: string | null }
            | { first_name: string | null; last_name: string | null; phone: string | null }[]
            | null;
        };
        const p = Array.isArray(raw.patient) ? raw.patient[0] : raw.patient;
        return {
          id: raw.id,
          patient_id: raw.patient_id,
          status: raw.status,
          arrival_type: raw.arrival_type,
          opened_at: raw.opened_at,
          patient_first_name: p?.first_name ?? null,
          patient_last_name: p?.last_name ?? null,
          patient_phone: p?.phone ?? null,
        };
      });
      setData(mapped);
      settle();
    })();
    return () => {
      cancelled = true;
    };
  }, [tick, settle]);

  // The In-Clinic page and the BottomNav counter both consume this hook.
  // Subscribing to lng_visits covers status flips (opened → in_progress
  // → done) and new arrivals; lng_appointments covers the moment an
  // appointment is marked arrived (which spawns the visit row that
  // belongs in this list).
  useRealtimeRefresh(
    [
      { table: 'lng_visits' },
      { table: 'lng_appointments' },
    ],
    refresh,
  );

  return { data, loading, error, refresh };
}

interface VisitDetailResult {
  visit: VisitRow | null;
  patient: PatientRow | null;
  deposit: AppointmentDeposit | null;
  shopifyOrder: AppointmentShopifyOrder | null;
  appointment: VisitAppointmentContext | null;
  // Display name of the receptionist who opened the visit. Resolved
  // from lng_visits.receptionist_id → accounts. Surfaces on printed
  // documents (LWO header) and the visit lifecycle strip; null when
  // the column isn't populated or the account row was deleted.
  receptionistName: string | null;
  loading: boolean;
  error: string | null;
  refresh: () => void;
}

export function useVisitDetail(visitId: string | undefined): VisitDetailResult {
  const [visit, setVisit] = useState<VisitRow | null>(null);
  const [patient, setPatient] = useState<PatientRow | null>(null);
  const [deposit, setDeposit] = useState<AppointmentDeposit | null>(null);
  const [shopifyOrder, setShopifyOrder] = useState<AppointmentShopifyOrder | null>(null);
  const [appointment, setAppointment] = useState<VisitAppointmentContext | null>(null);
  const [receptionistName, setReceptionistName] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [tick, setTick] = useState(0);
  const { loading, settle } = useStaleQueryLoading(visitId);

  const refresh = useCallback(() => setTick((t) => t + 1), []);

  useEffect(() => {
    if (!visitId) {
      settle();
      return;
    }
    let cancelled = false;
    (async () => {
      const { data: v, error: ve } = await supabase
        .from('lng_visits')
        .select('*')
        .eq('id', visitId)
        .maybeSingle();
      if (cancelled) return;
      if (ve) {
        setError(ve.message);
        settle();
        return;
      }
      setVisit(v as VisitRow);
      if (v) {
        const visitRow = v as VisitRow;
        const { data: p } = await supabase
          .from('patients')
          .select(
            // avatar_data joins the standard PatientRow fields so the
            // visit hero can show a real avatar instead of always
            // falling back to initials. Mirrors the AppointmentDetail
            // patient fetch shape.
            'id, location_id, internal_ref, first_name, last_name, email, phone, date_of_birth, shopify_customer_id, avatar_data'
          )
          .eq('id', visitRow.patient_id)
          .maybeSingle();
        if (!cancelled) setPatient(p as (PatientRow & { avatar_data?: string | null }) | null);

        // Pull the deposit + intake refs off the linked appointment (if
        // any). For walk-ins, pull the same shape from lng_walk_ins so
        // the visit page doesn't have to special-case which kind it
        // is. The 42703 fallback survives a frontend deploy that lands
        // before the appointment_ref / jb_ref migrations.
        if (visitRow.appointment_id) {
          const { data: appt, error: apptErr } = await supabase
            .from('lng_appointments')
            .select(
              'id, notes, customer_note, event_type_label, intake, deposit_pence, deposit_currency, deposit_provider, deposit_status, shopify_order_id, shopify_order_name, shopify_order_total_pence, shopify_order_currency, appointment_ref, jb_ref, created_at, start_at, end_at, location_id, source, brand_id, paid_in_full_at_booking, service_type, arch, product_key, repair_variant, free_upgrade, free_upgrade_reason'
            )
            .eq('id', visitRow.appointment_id)
            .maybeSingle();
          if (!cancelled && !apptErr && appt) {
            const a = appt as {
              id: string;
              notes: string | null;
              customer_note: string | null;
              event_type_label: string | null;
              intake: Array<{ question: string; answer: string }> | null;
              deposit_pence: number | null;
              deposit_currency: string | null;
              deposit_provider: 'paypal' | 'stripe' | null;
              deposit_status: 'paid' | 'failed' | null;
              shopify_order_id: string | null;
              shopify_order_name: string | null;
              shopify_order_total_pence: number | null;
              shopify_order_currency: string | null;
              appointment_ref: string | null;
              jb_ref: string | null;
              created_at: string;
              start_at: string;
              end_at: string | null;
              location_id: string | null;
              source: string | null;
              brand_id: 'venneir' | 'denture' | null;
              paid_in_full_at_booking: boolean | null;
              service_type: string | null;
              arch: string | null;
              product_key: string | null;
              repair_variant: string | null;
              free_upgrade: boolean | null;
              free_upgrade_reason: string | null;
            };
            setAppointment({
              id: a.id,
              notes: a.notes,
              customer_note: a.customer_note ?? null,
              event_type_label: a.event_type_label,
              intake: a.intake,
              appointment_ref: a.appointment_ref ?? null,
              jb_ref: a.jb_ref ?? null,
              created_at: a.created_at,
              start_at: a.start_at,
              end_at: a.end_at,
              location_id: a.location_id,
              source: a.source,
              service_type: a.service_type ?? null,
              arch: a.arch ?? null,
              product_key: a.product_key ?? null,
              repair_variant: a.repair_variant ?? null,
              free_upgrade: a.free_upgrade ?? false,
              free_upgrade_reason: a.free_upgrade_reason ?? null,
            });
            if (
              a.deposit_pence != null &&
              a.deposit_pence > 0 &&
              a.deposit_provider &&
              a.deposit_status
            ) {
              setDeposit({
                pence: a.deposit_pence,
                currency: a.deposit_currency ?? 'GBP',
                provider: a.deposit_provider,
                status: a.deposit_status,
                source: a.source,
                brandId: a.brand_id,
                paidInFullAtBooking: a.paid_in_full_at_booking ?? false,
              });
            } else {
              setDeposit(null);
            }
            if (
              a.shopify_order_id
              && a.shopify_order_name
              && typeof a.shopify_order_total_pence === 'number'
              && a.shopify_order_total_pence > 0
            ) {
              setShopifyOrder({
                id: a.shopify_order_id,
                name: a.shopify_order_name,
                pence: a.shopify_order_total_pence,
                currency: a.shopify_order_currency ?? 'GBP',
              });
            } else {
              setShopifyOrder(null);
            }
          }
        } else if (visitRow.walk_in_id) {
          const { data: wk, error: wkErr } = await supabase
            .from('lng_walk_ins')
            .select('service_type, appointment_ref, jb_ref, created_at')
            .eq('id', visitRow.walk_in_id)
            .maybeSingle();
          if (!cancelled && !wkErr && wk) {
            const w = wk as {
              service_type: string | null;
              appointment_ref: string | null;
              jb_ref: string | null;
              created_at: string;
            };
            setAppointment({
              // Walk-ins have no lng_appointments row; use the
              // walk-in id as a stand-in. AppointmentNotesHero is
              // gated below so it's never rendered for walk-ins,
              // but the field still has to be a string to satisfy
              // the shared context shape.
              id: visitRow.walk_in_id,
              notes: null,
              customer_note: null,
              event_type_label: w.service_type, // best-effort label for the catalogue picker
              intake: null,
              appointment_ref: w.appointment_ref ?? null,
              jb_ref: w.jb_ref ?? null,
              // Walk-ins have no booking lifecycle, but VisitDetail
              // expects these fields shaped the same as appointments
              // — gating on arrival_type keeps Booked/Scheduled
              // lines off the page for walk-ins.
              created_at: w.created_at,
              start_at: w.created_at,
              end_at: null,
              location_id: null,
              source: 'walk_in',
              // Walk-ins have no axis pins. service_type carries
              // the picked service label for cart suggestions; arch
              // and product_key default to null so the hero falls
              // back to the legacy humaniseEventTypeLabel path
              // rather than trying to compose "Upper Walk-in" or
              // similar.
              service_type: w.service_type ?? null,
              arch: null,
              product_key: null,
              repair_variant: null,
              free_upgrade: false,
              free_upgrade_reason: null,
            });
            setDeposit(null);
          } else {
            setAppointment(null);
            setDeposit(null);
          }
        } else {
          setAppointment(null);
          setDeposit(null);
        }

        // Resolve the receptionist's display name. lng_visits stores
        // an account id; the printable LWO and any future audit
        // surface need a human-readable name. A missing account row
        // (deleted staff) leaves the name null and downstream renders
        // a dash — it never blocks the visit page from loading.
        if (visitRow.receptionist_id) {
          const { data: acct } = await supabase
            .from('accounts')
            .select('name, first_name, last_name')
            .eq('id', visitRow.receptionist_id)
            .maybeSingle();
          if (!cancelled) {
            const a = acct as { name: string | null; first_name: string | null; last_name: string | null } | null;
            const composed =
              (a?.name && a.name.trim()) ||
              [a?.first_name, a?.last_name].filter(Boolean).join(' ').trim();
            setReceptionistName(composed || null);
          }
        } else if (!cancelled) {
          setReceptionistName(null);
        }
      }
      settle();
    })();
    return () => {
      cancelled = true;
    };
  }, [visitId, tick, settle]);

  // Visit detail refreshes when its visit row, the linked appointment
  // (deposit status, JB ref, intake), or the underlying patient row
  // changes — so opening the till or running the customers/update
  // webhook is reflected on the page without a reload.
  useRealtimeRefresh(
    visitId
      ? [
          { table: 'lng_visits', filter: `id=eq.${visitId}` },
          { table: 'lng_appointments' },
          { table: 'patients' },
        ]
      : [],
    refresh,
  );

  return { visit, patient, deposit, shopifyOrder, appointment, receptionistName, loading, error, refresh };
}

// ---------- Unsuitability ----------

// Visit-level early-end reason. 'unsuitable' is the per-product
// clinical path (still preferred via the Mark unsuitable / per-line
// trash flows since it captures lng_unsuitability_records). The
// other categories cover the cases where there's no per-product
// finding to record — patient walked out, wrong booking, etc.
export type VisitEndReason =
  | 'unsuitable'
  | 'patient_declined'
  | 'patient_walked_out'
  | 'wrong_booking'
  | 'other';

// One picked line in the unsuitable end-visit flow. Sent as the
// `picks` array on the RPC so each soft-delete + unsuitability
// record write lands in the same transaction as the visit status
// flip — no half-state if the client tab closes mid-loop, which
// was the failure mode before this change.
export interface EndVisitEarlyPick {
  cart_item_id: string;
  catalogue_id: string;
}

export interface EndVisitEarlyInput {
  patient_id: string;
  visit_id: string;
  reason: VisitEndReason;
  note: string;
  // Required when reason='unsuitable'; ignored for the other
  // categories (those soft-delete every active cart line).
  picks?: EndVisitEarlyPick[];
}

// End an active visit. Thin wrapper around lng_end_visit_early,
// which owns the multi-write transaction (cart soft-deletes,
// unsuitability records, visit status flip, timeline events).
//
// Two branches inside the RPC:
//
//   • reason='unsuitable': p_picks identifies which catalogue-
//     backed lines to remove. Soft-deletes them with
//     removed_reason='unsuitable', writes one
//     lng_unsuitability_records row per pick, and one
//     'cart_line_removed' patient_events row per pick so the
//     timeline keeps its per-item rows. Visit flips to 'unsuitable'.
//
//   • reason ∈ ('patient_declined','patient_walked_out',
//     'wrong_booking','other'): soft-deletes every active cart line
//     with removed_reason='visit_ended_early' — a distinct value
//     from manual 'changed_mind' removals so reverse can restore
//     them cleanly. Visit flips to 'ended_early'.
//
// In both branches the RPC writes one visit-level
// 'visit_ended_early' patient_events row that visitTimeline.ts
// already renders as "Visit ended early — <reason>".
export async function endVisitEarly(input: EndVisitEarlyInput): Promise<void> {
  const note = input.note.trim();
  if (note.length === 0) throw new Error('A reason is required to end the visit early');
  if (input.reason === 'unsuitable' && (!input.picks || input.picks.length === 0)) {
    throw new Error('Pick at least one product the patient was unsuitable for.');
  }

  const { error } = await supabase.rpc('lng_end_visit_early', {
    p_visit_id: input.visit_id,
    p_patient_id: input.patient_id,
    p_reason: input.reason,
    p_note: note,
    p_picks: input.reason === 'unsuitable' ? (input.picks ?? []) : [],
  });
  if (error) throw new Error(error.message);
}

export interface ReverseUnsuitabilityInput {
  patient_id: string;
  visit_id: string;
}

// How the work was handed off at completion.
export type VisitFulfilmentMethod = 'in_person' | 'shipping';

// Looks at the active cart for the visit and decides whether the
// Complete visit flow needs to ask the in-person / shipping
// question. Returns false when every active line came from a
// catalogue row with fulfilment_required=false (virtual sessions,
// in-person impression appointments). Returns true when at least
// one line still needs a fulfilment decision — that's the safe
// default whenever we can't read the catalogue or the cart contains
// a free-form (no catalogue_id) line, since asking is preferable to
// silently auto-completing a real handover.
export async function visitRequiresFulfilment(visitId: string): Promise<boolean> {
  const { data: cart } = await supabase
    .from('lng_carts')
    .select('id')
    .eq('visit_id', visitId)
    .maybeSingle();
  const cartId = (cart as { id: string } | null)?.id;
  if (!cartId) return true;

  const { data: rows, error } = await supabase
    .from('lng_cart_items')
    .select('catalogue_id')
    .eq('cart_id', cartId)
    .is('removed_at', null);
  if (error) return true;

  const items = (rows ?? []) as Array<{ catalogue_id: string | null }>;
  if (items.length === 0) return false;

  // Any ad-hoc line (no catalogue_id) forces the question — we can't
  // know what it represents physically.
  if (items.some((i) => !i.catalogue_id)) return true;

  const catalogueIds = Array.from(
    new Set(items.map((i) => i.catalogue_id).filter((id): id is string => !!id)),
  );
  if (catalogueIds.length === 0) return true;

  const { data: cat, error: catErr } = await supabase
    .from('lwo_catalogue')
    .select('id, fulfilment_required')
    .in('id', catalogueIds);
  if (catErr) return true;

  const flagById = new Map<string, boolean>();
  for (const row of (cat ?? []) as Array<{ id: string; fulfilment_required: boolean }>) {
    flagById.set(row.id, row.fulfilment_required);
  }

  // Default to requiring fulfilment when a catalogue row is missing
  // (renamed / deleted) so we never silently auto-complete a real
  // physical handover.
  return items.some((i) => flagById.get(i.catalogue_id!) !== false);
}

export interface CompleteVisitInput {
  patient_id: string;
  visit_id: string;
  appointment_id: string | null;
  walk_in_id: string | null;
  // Null means "no fulfilment needed for this visit" — every active
  // cart line came from a catalogue row with fulfilment_required=false
  // (virtual sessions, in-person impression appointments). The Complete
  // visit flow skips the fulfilment sheet in this case and finishes
  // directly. Non-null records the staff's in-person/shipping choice.
  fulfilment_method: VisitFulfilmentMethod | null;
  // Total in pence — used purely for the timeline event payload so
  // the closed event reads "£298.00" without a join back to the
  // cart roll-up.
  total_pence?: number;
}

// Explicit visit completion. Until now Pay auto-completed the visit
// when staff sent the receipt; that conflated payment with hand-off
// and skipped the in-person-vs-shipping question. Now staff has to
// click Complete visit on VisitDetail and answer the fulfilment
// question, which lands as fulfilment_method on the visit row for a
// future shipping flow to pick up.
//
// Side effects:
//   - flips lng_visits.status='complete' + stamps closed_at
//   - records fulfilment_method (in_person | shipping)
//   - frees the job box on the appointment / walk_in source so the
//     box becomes available for the next booking (the visit's own
//     jb_ref column is captured at insert and stays as audit)
//   - writes a patient_events 'visit_closed' row with the staff
//     account and the fulfilment choice on the payload
export async function completeVisit(input: CompleteVisitInput): Promise<void> {
  const { data: accountId } = await supabase.rpc('auth_account_id');

  const closedAt = new Date().toISOString();

  const { error: visitErr } = await supabase
    .from('lng_visits')
    .update({
      status: 'complete',
      closed_at: closedAt,
      fulfilment_method: input.fulfilment_method,
    })
    .eq('id', input.visit_id);
  if (visitErr) throw new Error(visitErr.message);

  // Seal the cart at the same moment as the visit. Without this a
  // free-visit (£0 balance) cart stays status='open' after Complete
  // because maybeFlipCartPaid only flips carts whose succeeded
  // payments meet a positive total — a £0 cart never trips that
  // condition. The open-after-complete state was both visually
  // confusing ("Cart open" pill on a Complete visit) and editable
  // (staff or an automated path could still add lines / discounts
  // against a visit that's already been physically handed off).
  // We close the cart unconditionally on completion; the UI gates
  // Complete visit on the cart already being settled (paid in full
  // or £0), so flipping to status='paid' here is consistent with
  // what the receptionist already saw before clicking Complete.
  await supabase
    .from('lng_carts')
    .update({ status: 'paid', closed_at: closedAt })
    .eq('visit_id', input.visit_id)
    .eq('status', 'open');

  // Free the JB and flip the source row to 'complete' so the
  // schedule calendar shows the appointment/walk-in as done.
  // The visit's own captured jb_ref is immutable and survives
  // this clearing, so the timeline + history stay intact.
  if (input.appointment_id) {
    const { error } = await supabase
      .from('lng_appointments')
      .update({ jb_ref: null, status: 'complete' })
      .eq('id', input.appointment_id);
    if (error) {
      await logFailure({
        source: 'visits.completeVisit.appointment_status',
        severity: 'error',
        message: `Visit completed but the appointment row did not flip to complete: ${error.message}`,
        context: { visit_id: input.visit_id, appointment_id: input.appointment_id },
      });
    }
  }
  if (input.walk_in_id) {
    const { error: walkInErr } = await supabase
      .from('lng_walk_ins')
      .update({ jb_ref: null })
      .eq('id', input.walk_in_id);
    if (walkInErr) {
      await logFailure({
        source: 'visits.completeVisit.walk_in_jb',
        severity: 'error',
        message: `Visit completed but the walk-in job box was not freed: ${walkInErr.message}`,
        context: { visit_id: input.visit_id, walk_in_id: input.walk_in_id },
      });
    }

    // Walk-ins carry a second row the schedule actually reads: the
    // calendar marker in lng_appointments written by openWalkInVisit
    // with status='arrived' and walk_in_id pointing back here. The
    // visit's own appointment_id stays NULL for walk-ins (the
    // exactly-one constraint on lng_visits forces walk_in_id
    // instead), so the branch above never fires for them and the
    // marker was left on 'arrived' forever. isAppointmentDimmed
    // treats 'arrived' as an active visit and refuses to dim it at
    // any age, so a fully processed walk-in kept rendering at full
    // strength with an "Arrived" pill days after the patient left.
    // Flip the marker here so walk-ins reach the same terminal
    // state as booked appointments. Status only: a walk-in's job box
    // lives on lng_walk_ins.jb_ref (the marker is inserted without
    // one, and clinicBoard reads the walk-in row for it), and the
    // branch above already freed it.
    const { error: markerErr } = await supabase
      .from('lng_appointments')
      .update({ status: 'complete' })
      .eq('walk_in_id', input.walk_in_id);
    if (markerErr) {
      await logFailure({
        source: 'visits.completeVisit.walk_in_marker_status',
        severity: 'error',
        message: `Visit completed but the walk-in calendar marker did not flip to complete: ${markerErr.message}`,
        context: { visit_id: input.visit_id, walk_in_id: input.walk_in_id },
      });
    }
  }

  await supabase.from('patient_events').insert({
    patient_id: input.patient_id,
    event_type: 'visit_closed',
    actor_account_id: (accountId as string | null) ?? null,
    payload: {
      visit_id: input.visit_id,
      total_pence: input.total_pence ?? null,
      fulfilment_method: input.fulfilment_method,
      staff_account_id: (accountId as string | null) ?? null,
    },
  });
}

// Switch a completed visit's fulfilment method after the fact. Customers
// sometimes change their mind between the visit and dispatch — we need
// to support flipping in_person → shipping and back without forcing the
// receptionist to "uncomplete" and redo the whole closing flow.
//
// Guard rails:
//   • Caller must pass the currently-stored method so a stale-page
//     submission can't silently overwrite a more recent change.
//   • Once a DPD label is issued (visit.dispatch_ref set), we refuse
//     to switch — orphaning a live shipment is worse than the customer
//     waiting for a manual cancel. The UI surfaces this state with a
//     "cancel the shipment first" note instead of the change button.
//   • Switching FROM shipping to in_person clears the
//     shipping_email_sent_at lock so a future shipping decision isn't
//     blocked by the atomic-claim that prevented duplicate emails.
//
// Audit:
//   patient_events 'visit_fulfilment_method_changed' with the old + new
//   methods, the visit id, and the actor. The timeline reads it via the
//   existing patient-events fetcher.
export interface UpdateVisitFulfilmentMethodInput {
  visit_id: string;
  patient_id: string;
  expected_current_method: VisitFulfilmentMethod;
  next_method: VisitFulfilmentMethod;
}

export type UpdateVisitFulfilmentMethodResult =
  | { ok: true; method: VisitFulfilmentMethod }
  | { ok: false; reason: 'no_change' | 'shipment_dispatched' | 'stale_method' | 'not_found' | 'update_failed'; detail?: string };

export async function updateVisitFulfilmentMethod(
  input: UpdateVisitFulfilmentMethodInput,
): Promise<UpdateVisitFulfilmentMethodResult> {
  if (input.expected_current_method === input.next_method) {
    return { ok: false, reason: 'no_change' };
  }

  // Re-read the row inside the same call so we catch a concurrent
  // change between the staff member opening the sheet and pressing
  // Confirm. The dispatch_ref check has to run against fresh data,
  // not the page's stale visit prop.
  const { data: fresh, error: readErr } = await supabase
    .from('lng_visits')
    .select('id, fulfilment_method, dispatch_ref')
    .eq('id', input.visit_id)
    .maybeSingle();
  if (readErr || !fresh) {
    return { ok: false, reason: 'not_found', detail: readErr?.message };
  }
  const current = (fresh as { fulfilment_method: VisitFulfilmentMethod | null }).fulfilment_method;
  if (current !== input.expected_current_method) {
    return { ok: false, reason: 'stale_method', detail: `Server has '${current}' (you saw '${input.expected_current_method}'). Refresh and try again.` };
  }
  const dispatchRef = (fresh as { dispatch_ref: string | null }).dispatch_ref;
  if (dispatchRef) {
    return { ok: false, reason: 'shipment_dispatched', detail: dispatchRef };
  }

  const patch: Record<string, unknown> = { fulfilment_method: input.next_method };
  // Free the dispatch-email lock when leaving shipping so the next
  // shipping attempt (if the customer flips again, or this same staff
  // member changes their mind) can re-send.
  if (input.expected_current_method === 'shipping' && input.next_method === 'in_person') {
    patch.shipping_email_sent_at = null;
  }

  const { error: updateErr } = await supabase
    .from('lng_visits')
    .update(patch)
    .eq('id', input.visit_id);
  if (updateErr) {
    return { ok: false, reason: 'update_failed', detail: updateErr.message };
  }

  const { data: accountId } = await supabase.rpc('auth_account_id');
  await supabase.from('patient_events').insert({
    patient_id: input.patient_id,
    event_type: 'visit_fulfilment_method_changed',
    actor_account_id: (accountId as string | null) ?? null,
    payload: {
      visit_id: input.visit_id,
      from_method: input.expected_current_method,
      to_method: input.next_method,
      staff_account_id: (accountId as string | null) ?? null,
    },
  });

  return { ok: true, method: input.next_method };
}

// Single entry point for the cart-line Remove sheet. Handles all
// three reason categories in one call: soft-deletes the line,
// writes the right audit row(s), and decides whether the visit
// should terminate as a result.
//
// Termination rule: visit flips to status='unsuitable' when the
// cart becomes empty AND at least one unsuitability record exists
// on this visit (in this removal or a prior one). Mixed visits
// where some removals were mistakes and at least one was
// unsuitable still terminate. Cart-empty-by-mistake-only visits
// stay active so staff can re-add.
export interface RemoveCartLineWithReasonInput {
  cart_item_id: string;
  catalogue_id: string | null; // required for 'unsuitable'
  visit_id: string;
  patient_id: string;
  reason: 'mistake' | 'changed_mind' | 'unsuitable';
  note?: string;
}

export async function removeCartLineWithReason(
  input: RemoveCartLineWithReasonInput
): Promise<{ visit_terminated: boolean }> {
  const { data, error } = await supabase.rpc('lng_remove_cart_line', {
    p_cart_item_id: input.cart_item_id,
    p_visit_id: input.visit_id,
    p_patient_id: input.patient_id,
    p_reason: input.reason,
    p_note: input.note ?? '',
    p_catalogue_id: input.catalogue_id,
  });
  if (error) throw new Error(error.message);
  const row = Array.isArray(data) ? (data[0] as { visit_terminated: boolean } | undefined) : null;
  return { visit_terminated: row?.visit_terminated === true };
}

// Reverse a visit that terminated as 'unsuitable' or 'ended_early'.
// Thin wrapper around lng_reverse_visit_end, which owns the atomic
// reverse transaction: restore the lines whose removed_reason
// signals they were taken by the visit-end action (unsuitable or
// visit_ended_early), reopen the visit, and write the timeline
// event.
//
// The reverse contract — only lines that were removed BY the
// visit-end action come back. Mid-visit 'mistake' and
// 'changed_mind' removals stay removed so the refunds already
// issued against those removals stay reconciled. (Earlier
// behaviour was "restore everything", which broke the cart vs
// refund accounting when a mid-visit refund pre-dated the visit-
// end action — see 20260519000006 migration header for the
// reasoning.)
//
// lng_unsuitability_records are immutable clinical audit and are
// never deleted by reverse — only the cart-item soft-delete is
// un-flagged.
export async function reverseUnsuitability(input: ReverseUnsuitabilityInput): Promise<void> {
  const { error } = await supabase.rpc('lng_reverse_visit_end', {
    p_visit_id: input.visit_id,
    p_patient_id: input.patient_id,
    p_note: null,
  });
  if (error) throw new Error(error.message);
}

// Latest end-of-visit details (either path: 'unsuitable' or
// 'ended_early'). The header lifecycle line uses these to render
// "Marked Unsuitable [time] / By [name]" or "Visit Ended Early
// [time] / By [name]". Null while the visit is still active.
//
// For 'unsuitable' the staff name comes from lng_unsuitability_records
// (the latest record's recorded_by). For 'ended_early' it comes
// from the latest patient_events row of type 'visit_ended_early'
// matching this visit.
export interface LatestUnsuitability {
  recorded_at: string;
  // The reason text shown beneath the header line. For unsuitable
  // it's the lng_unsuitability_records.reason from the latest
  // record; for ended_early it's lng_visits.visit_end_note.
  reason: string;
  recorded_by_name: string | null;
  // Discriminator so the header can render the right label.
  category: 'unsuitable' | 'ended_early';
  // Sub-category for 'ended_early' visits (patient_declined,
  // patient_walked_out, wrong_booking, other). Null when category
  // is 'unsuitable'.
  end_reason: VisitEndReason | null;
}

interface LatestUnsuitabilityResult {
  data: LatestUnsuitability | null;
  loading: boolean;
  error: string | null;
}

interface AccountJoin {
  first_name: string | null;
  last_name: string | null;
  name: string | null;
}

function displayAccountName(a: AccountJoin | AccountJoin[] | null | undefined): string | null {
  const flat = Array.isArray(a) ? a[0] ?? null : a ?? null;
  if (!flat) return null;
  const fn = flat.first_name?.trim();
  const ln = flat.last_name?.trim();
  if (fn && ln) return `${fn} ${ln}`;
  return fn ?? ln ?? flat.name?.trim() ?? null;
}

export function useLatestUnsuitability(visitId: string | null): LatestUnsuitabilityResult {
  const [data, setData] = useState<LatestUnsuitability | null>(null);
  const [error, setError] = useState<string | null>(null);
  const { loading, settle } = useStaleQueryLoading(visitId);

  useEffect(() => {
    if (!visitId) {
      setData(null);
      settle();
      return;
    }
    let cancelled = false;
    (async () => {
      // Step A: read the visit row to learn status + end reason/note.
      // Visits not in a terminal status return null — the header
      // shouldn't surface anything until the visit ends.
      const { data: vRow, error: vErr } = await supabase
        .from('lng_visits')
        .select('status, closed_at, visit_end_reason, visit_end_note')
        .eq('id', visitId)
        .maybeSingle();
      if (cancelled) return;
      if (vErr) {
        setError(vErr.message);
        settle();
        return;
      }
      const v = vRow as {
        status: string | null;
        closed_at: string | null;
        visit_end_reason: VisitEndReason | null;
        visit_end_note: string | null;
      } | null;
      if (!v || (v.status !== 'unsuitable' && v.status !== 'ended_early')) {
        setData(null);
        settle();
        return;
      }

      // Step B: pull the staff name. For 'unsuitable' we have the
      // recorded_by FK on the latest lng_unsuitability_records row;
      // for 'ended_early' it lives on the patient_events row this
      // function emits.
      if (v.status === 'unsuitable') {
        const { data: row, error: err } = await supabase
          .from('lng_unsuitability_records')
          .select('recorded_at, reason, account:accounts!recorded_by ( first_name, last_name, name )')
          .eq('visit_id', visitId)
          .order('recorded_at', { ascending: false })
          .limit(1)
          .maybeSingle();
        if (cancelled) return;
        if (err) {
          if (err.code === '42P01' || err.code === 'PGRST200') {
            setData(null);
            setError(null);
          } else {
            setError(err.message);
          }
          settle();
          return;
        }
        const r = row as { recorded_at: string; reason: string; account: AccountJoin | AccountJoin[] | null } | null;
        if (!r) {
          // status='unsuitable' without a record is the migration-
          // backfilled case; fall back to the visit's own end note
          // and skip the staff name.
          setData({
            recorded_at: v.closed_at ?? new Date(0).toISOString(),
            reason: v.visit_end_note ?? '',
            recorded_by_name: null,
            category: 'unsuitable',
            end_reason: null,
          });
          settle();
          return;
        }
        setData({
          recorded_at: r.recorded_at,
          reason: r.reason,
          recorded_by_name: displayAccountName(r.account),
          category: 'unsuitable',
          end_reason: null,
        });
        settle();
        return;
      }

      // status === 'ended_early'
      const { data: peRow, error: peErr } = await supabase
        .from('patient_events')
        .select('created_at, actor_account_id, account:accounts!actor_account_id ( first_name, last_name, name )')
        .eq('event_type', 'visit_ended_early')
        .filter('payload->>visit_id', 'eq', visitId)
        .order('created_at', { ascending: false })
        .limit(1)
        .maybeSingle();
      if (cancelled) return;
      if (peErr && peErr.code !== '42P01' && peErr.code !== 'PGRST200') {
        setError(peErr.message);
        settle();
        return;
      }
      const pe = peRow as { created_at: string; account: AccountJoin | AccountJoin[] | null } | null;
      setData({
        recorded_at: pe?.created_at ?? v.closed_at ?? new Date(0).toISOString(),
        reason: v.visit_end_note ?? '',
        recorded_by_name: displayAccountName(pe?.account),
        category: 'ended_early',
        end_reason: v.visit_end_reason,
      });
      settle();
    })();
    return () => {
      cancelled = true;
    };
  }, [visitId, settle]);

  return { data, loading, error };
}
