-- ─────────────────────────────────────────────────────────────────────────────
-- Lounge — patient-side booking management token
--
-- Customer self-serve cancel/reschedule from the booking widget
-- needs a way for an unauth'd patient to identify their own
-- booking without exposing any PII or enumeration vector. We hand
-- them an unguessable random uuid in the confirmation email
-- (`?token=<uuid>` in the manage URL), and every patient-facing
-- read or mutation is keyed on that token. No way to list
-- bookings; no way to read someone else's; no way to brute-force
-- the 122-bit token in any reasonable timeframe.
--
-- The token survives the booking lifecycle so an old confirmation
-- email's link still loads the cancelled state; the lookup RPC
-- returns the current row regardless of status. Mutations gate on
-- status (cancel only allowed when booked).
--
-- Two database objects in this migration:
--
--   1. lng_appointments.manage_token uuid — populated by default
--      on INSERT, backfilled for existing rows so any past
--      Calendly / manual / native row can be retroactively
--      managed if we want to email a manage link later.
--
--   2. lng_widget_lookup_booking(p_token) — SECURITY DEFINER
--      anon-callable function returning the patient-visible
--      shape. NEVER leaks email, phone, internal notes, staff
--      assignments, or any other patient's data. The first_name
--      is included only for the greeting; could be omitted if a
--      stricter auditor objects.
--
-- Rollback:
--   drop function public.lng_widget_lookup_booking(uuid);
--   alter table public.lng_appointments drop column manage_token;
-- ─────────────────────────────────────────────────────────────────────────────

-- ── Column ────────────────────────────────────────────────────
alter table public.lng_appointments
  add column if not exists manage_token uuid not null default gen_random_uuid();

create unique index if not exists lng_appointments_manage_token_unique
  on public.lng_appointments (manage_token);

comment on column public.lng_appointments.manage_token is
  'Random uuid handed to the patient via the confirmation email so they can cancel or reschedule from /widget/manage. Unguessable; survives status changes (an old email''s link loads the cancelled state). Generated by default on insert.';

-- ── Patient-visible lookup ───────────────────────────────────
create or replace function public.lng_widget_lookup_booking(
  p_token uuid
)
returns table (
  appointment_ref     text,
  status              text,
  service_type        text,
  service_label       text,
  start_at            timestamptz,
  end_at              timestamptz,
  location_name       text,
  location_address    text,
  patient_first_name  text,
  deposit_status      text,
  deposit_pence       int,
  deposit_currency    text,
  cancellable         boolean
)
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  select
    a.appointment_ref,
    a.status,
    a.service_type,
    coalesce(nullif(a.event_type_label, ''), a.service_type) as service_label,
    a.start_at,
    a.end_at,
    coalesce(l.name, 'Venneir Lounge')                       as location_name,
    -- Compose the address line the same way lng_widget_locations
    -- does so the manage page reads identically to the picker.
    trim(both ', ' from concat_ws(', ',
      nullif(l.address, ''),
      nullif(l.city, '')
    ))                                                        as location_address,
    p.first_name                                              as patient_first_name,
    a.deposit_status,
    a.deposit_pence,
    a.deposit_currency,
    -- A booking is patient-cancellable while it's still in the
    -- "booked" state and starts in the future. Staff can still
    -- cancel via the Schedule sheet at any point — those go
    -- through a different RLS path.
    (a.status = 'booked' and a.start_at > now())              as cancellable
  from public.lng_appointments a
  left join public.locations l on l.id = a.location_id
  left join public.patients p on p.id = a.patient_id
  where a.manage_token = p_token
  limit 1;
end;
$$;

revoke all on function public.lng_widget_lookup_booking(uuid) from public;
grant execute on function public.lng_widget_lookup_booking(uuid) to anon, authenticated, service_role;

comment on function public.lng_widget_lookup_booking(uuid) is
  'Patient-side booking lookup for the manage page. Anon-callable. Returns the safe shape — service / location / time / status / deposit / first name only — never email, phone, notes, staff assignments, or any other patient''s row. Returns no rows for an unknown token (the manage page renders a "link not valid" state).';
